Parameters:
  Subnet1:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public subnet."
  Subnet2:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public subnet."
  dbIdentifier:
    Type: String
    Description: To be passed from the parent template.
  dbName:
    Type: String
    Description: To be passed from the parent template.
  dbUser:
    Type: String
    Description: To be passed from the parent template.
  dbPort:
    Type: Number
    Description: To be passed from the parent template.

Resources:
  QuickHopDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet for QuickHop RDS"
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
      DBSubnetGroupName: "quickhop-db-subnet-group"

  QuickHopDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref dbIdentifier
      AllocatedStorage: 20
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      MasterUsername: !Ref dbUser
      ManageMasterUserPassword: true
      VPCSecurityGroups:
        - !ImportValue DBSecurityGroupId
      DBSubnetGroupName: !Ref QuickHopDBSubnetGroup # Reference the Subnet Group here
      PubliclyAccessible: true
      DBName: !Ref dbName
      Port: !Ref dbPort
      MultiAZ: false # Avoids replication
      BackupRetentionPeriod: 0 # Disables automated snapshots

  ## Save data to SSM to be used later in .env production (production environment variables)
  QuickHopDBHostParameterPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/dbPassword"
      Type: String
      Value: !GetAtt QuickHopDB.MasterUserSecret.SecretArn

  QuickHopDBHostParameterEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/dbEndpoint"
      Type: String
      Value: !GetAtt QuickHopDB.Endpoint.Address

Outputs:
  DBPasswordArn:
    Description: "Secret password created for RDS instance in Secrets Manager"
    Value: !GetAtt QuickHopDB.MasterUserSecret.SecretArn
    Export:
      Name: DBPasswordArn
  DBHost:
    Description: "DB endpoint/DB Host"
    Value: !GetAtt QuickHopDB.Endpoint.Address
    Export:
      Name: DBHost
