Parameters:
  awsRegion:
    Type: String
    Description: Region to create the resources on.

  awsS3BucketName:
    Type: String
    Description: The bucket must already exist to upload/download files from.

  cognitoDomain:
    Type: String
    Description: Cognito domain.

  cognitoClientId:
    Type: String
    Description: The Client ID.

  cognitoRedirectUri:
    Type: String
    Description: Cognito redirect uri, that must end with /callback. This uri must be already configured in Cognito.

  googleClientId:
    Type: String
    Description: Google Client Id for SSO (to be used with Job Seeker Loign to the app).

  openaiApiKey:
    Type: String
    Description: OpenAI key to access the model.

  openaiModel:
    Type: String
    Description: OpenAI model type.

  backendBaseUrl:
    Type: String
    Description: API URL endpoint.

  allowedOrigin:
    Type: String
    Description: Provide frontend https url to be added as allowed origin in backend server.

  adminEmailId:
    Type: String
    Description: Any email to be used as an admin email to access backend.

  dbIdentifier:
    Type: String
    Description: The db name on the aws console.
    Default: quickhopdb

  dbName:
    Type: String
    Description: The actual db name.

  dbUser:
    Type: String
    Description: The username for the RDS database.
  
  recruitmentPhone:
    Type: String
    Description: Phone number assigned to the AWS Connect main IVR to receive the interview calls.
  
  dynamoDBTableInterviewees:
    Type: String
    Description: The table name to save interviewees information.
  
  dynamoDBTableInitialMessage:
    Type: String
    Description: The table name that stores the initial prompt message for the AI.
  
  dynamoDBTableCounter:
    Type: String
    Description: The table name that is used as a counter for each job post.

Resources:
  awsRegionSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/awsRegion"
      Type: String
      Value: !Ref awsRegion

  awsS3BucketNameSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/awsS3BucketName"
      Type: String
      Value: !Ref awsS3BucketName

  cognitoDomainSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/cognitoDomain"
      Type: String
      Value: !Ref cognitoDomain

  cognitoClientIdSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/cognitoClientId"
      Type: String
      Value: !Ref cognitoClientId

  cognitoRedirectUriSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/cognitoRedirectUri"
      Type: String
      Value: !Ref cognitoRedirectUri

  googleClientIdSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/googleClientId"
      Type: String
      Value: !Ref googleClientId

  openaiApiKeySSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/openaiApiKey"
      Type: String
      Value: !Ref openaiApiKey

  openaiModelSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/openaiModel"
      Type: String
      Value: !Ref openaiModel

  backendBaseUrlSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/backendBaseUrl"
      Type: String
      Value: !Ref backendBaseUrl

  allowedOriginSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/allowedOrigin"
      Type: String
      Value: !Ref allowedOrigin

  dbIdentifierSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/dbIdentifier"
      Type: String
      Value: !Ref dbIdentifier

  dbNameSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/dbName"
      Type: String
      Value: !Ref dbName

  dbUserSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/dbUser"
      Type: String
      Value: !Ref dbUser

  # dbPasswordSSMParameter:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Name: "/quickhop/dbPassword"
  #     Type: String
  #     Value: !Ref dbPassword

  adminEmailIdSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/adminEmailId"
      Type: String
      Value: !Ref adminEmailId
  
  recruitmentPhoneSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/recruitmentPhone"
      Type: String
      Value: !Ref recruitmentPhone
  
  dynamoDBTableIntervieweesSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/dynamoDBTableInterviewees"
      Type: String
      Value: !Ref dynamoDBTableInterviewees
  
  dynamoDBTableInitialMessageSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/dynamoDBTableInitialMessage"
      Type: String
      Value: !Ref dynamoDBTableInitialMessage
  
  dynamoDBTableCounterSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/quickhop/dynamoDBTableCounter"
      Type: String
      Value: !Ref dynamoDBTableCounter
